version: '2'
services:
    mysql:
        image: mariadb 
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: html
            MYSQL_USER: user
            MYSQL_PASSWORD: pwd

    maildev:
        image: djfarrelly/maildev
        ports:
            - 1080:80
            - 1025:25

    php:
        build: ./.docker/php
        ports:
            - 9000:9000
            - 9999:9999
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./html:/var/www/html
            - ./html/var/log:/logs/web-application
            - ~/.gitconfig:/root/.gitconfig
        links:
            - mysql
            - maildev

    nginx:
        image: nginx
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./html:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
